sudo: required
services:
  - docker

before_install:
  - docker build -t gzkatana/docker-react -f Dockerfile.dev .

scripts:
  #- docker run gzkatana/docker-react npm run test -- --coverage
  - docker run -e CI=true gzkatana/docker-react npm run test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gzkatana/docker-react

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIA5ECYDALW44GFTTMO"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-902127878893"
  bucker_path: "docker-react"
  skip_cleanup: true
  on:
    branch: master
  