sudo: required
services:
  - docker

before_install:
  - docker build -t gzkatana/docker-react -f Dockerfile.dev .

scripts:
  #- docker run gzkatana/docker-react npm run test -- --coverage
  - docker run -e CI=true gzkatana/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-902127878893"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"